parameters:
  HGT: [10, 15.5]
  Lstr: [0, 1]
  THK: [0.25, 0.6]
  ANG: [-10, 10]
  CVT: [0.1, 0.8]
  LAS: [0.2, 1.0]

objectives:
  - 1 - LMN_open
  - LMN_closed
  - Smax - Slim
  - HELI

num_candidates: 200
initial_samples: 150
n_iter: 10

hydra:
  run:
    dir: .