parameters:
  HGT: [10, 15.5]
  Lstr: [0, 1]
  THK: [0.25, 0.6]
  ANG: [-10, 10]
  CVT: [0.1, 0.8]
  LAS: [0.2, 1.0]

objectives:
  - LMN_open
  - -LMN_closed
  - Smax - Slim
  - -HELI

num_candidates: 100
initial_samples: 50
n_iter: 10
batch_size: 1

hydra:
  run:
    dir: .

termination_parameters:
  min_improvement: 1e-3
  no_improvement_generations: 5